# Nichtlineare Gleichungssysteme

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Gesucht ist das Minimum der Funktion f(x) = x^2 * sin(x) im Intervall [2, 7].


In [2]:
f_x = lambda x: x**2 * np.sin(x)
f_x_d = lambda x: 2*x*np.sin(x) + x**2*np.cos(x)
f_x_dd = lambda x: 2*np.sin(x) + 4*x*np.cos(x) - x**2*np.sin(x)

# Newton-Verfahren für f_x_d und f_x_dd
x = 5
tol = 10e-12
k = 0
res = abs(f_x_d(x))
while res > tol:
    x = x - f_x_d(x)/f_x_dd(x)
    res = abs(f_x_d(x))
    k=k+1
    print( x, res, k )


5.090076561209913 0.09181506958197794 1
5.086988481288664 0.00010048741784807191 2
5.086985094106357 1.212292488617095e-10 3
5.08698509410227 3.552713678800501e-15 4


# Mehrdimensionales Newton-Verfahren

In [3]:
x = (0.1, -0.1) # 2D-Startwert
tol = 1.e-100 # Abbruchtoleranz
k = 0
f = (2*x[0] + 4*x[1], 4*x[0] + 8*x[1]**3) # Auswertung von 2D-f in x
res = np.linalg.norm(f) # Norm von Vektor f
while res > tol:
    k = k + 1
    # mehrdimensionale Ableitung (Jacobimatrix) an Stelle x
    J = np.array([[2, 4], [4, 24*x[1]**2]])
    # x = x - J^(-1)*f %2D Newton
    # Gauss-Algorithmus, numerisch besser als d=inv(J)*f
    d = np.linalg.solve(J, f)
    x = x - d # 2D Newton-Schritt
    f = [2*x[0] + 4*x[1], 4*x[0] + 8*x[1]**3] # 2D-f an neuer Stelle x
    res = np.linalg.norm(f)
    print('x =', x, 'in', k, 'Schritten' )

x = [-0.00412371  0.00206186] in 1 Schritten
x = [ 3.50622930e-08 -1.75311465e-08] in 2 Schritten
x = [-1.98523347e-23  9.92616735e-24] in 3 Schritten
x = [0. 0.] in 4 Schritten


# Aufgabe 2

In [9]:
x = (-0.5, -0.5) # 2D-Startwert
tol = 1.e-10 # Abbruchtoleranz
k = 0
f = (x[0]**2 + x[1]**2 + 0.6*x[1] - 0.16, x[0]**2 - x[1]**2 + x[0] - 1.6*x[1] - 0.14) # funktion f (Vektor)
res = np.linalg.norm(f) # Norm von Vektor f
while res > tol:
    k = k + 1
    # mehrdimensionale Ableitung (Jacobimatrix) an Stelle x
    J = np.array([[2*x[0], 2*x[1] + 0.6], [2*x[0] + 1, -2*x[1] - 1.6]])
    # x = x - J^(-1)*f %2D Newton
    # Gauss-Algorithmus, numerisch besser als d=inv(J)*f
    d = np.linalg.solve(J, f)
    x = x - d # 2D Newton-Schritt
    f = (x[0]**2 + x[1]**2 + 0.6*x[1] - 0.16, x[0]**2 - x[1]**2 + x[0] - 1.6*x[1] - 0.14) # funktion f (Vektor)
    res = np.linalg.norm(f)
    print('x =', x, 'in', k, 'Schritten' )

x = [-0.56666667 -0.23333333] in 1 Schritten
x = [-0.50773606 -0.29908987] in 2 Schritten
x = [-0.50005985 -0.30005799] in 3 Schritten
x = [-0.50000001 -0.3       ] in 4 Schritten
x = [-0.5 -0.3] in 5 Schritten


# Aufgabe 3


In [ ]:
def newton(f, J, x0, tol=1.e-10):
    max_loops = 1000
    x = x0
    k = 0
    res = np.linalg.norm(f(x))
    while res > tol and k < max_loops:
        k += 1
        d = np.linalg.solve(J(x), f(x))
        x = x - d
        res = np.linalg.norm(f(x))
    return x, k

In [47]:
f = lambda x: np.array([x[0]**2 + x[0]*x[1]**3 - 9, 3*x[0]**2 * x[1] - x[1]**3 - 4])
J = lambda x: np.array([[2*x[0] + x[1]**3, 3*x[1]**2 * x[0]], [6*x[0] * x[1], 3*x[0]**2 - 3*x[1]**2]])

print(newton(f, J, np.array([0.1, 0.1])))
print(newton(f, J, np.array([1, 1])))
print(newton(f, J, np.array([3, 0])))

(array([-3.00162489,  0.14810799]), 27)
(array([1.33635538, 1.7542352 ]), 7)
(array([2.99836535, 0.14843098]), 3)
