In [15]:
import numpy as np

In [16]:
n = 22
A = np.vander(np.linspace(0,1,n))
x_exakt = np.ones(n)
b = A@x_exakt
x = np.linalg.solve(A,b)
print(np.linalg.norm(x-x_exakt)/np.linalg.norm(x_exakt)*100)

337.87252998241445


In [17]:
# Berechne die Konditionierung der Matrix A
A_inv = np.linalg.inv(A)
A_inv_A = np.linalg.norm(A_inv) * np.linalg.norm(A)
print(A_inv_A)

7.974834872133152e+17


# Aufgabe 6

In [18]:
def backsubst(U, y):
    # Berechnet die Loesung x von U x = y durch Rueckwaerts-Einsetzen
    # Dabei ist U eine rechte obere Dreiecksmatrix
    n = len(y)
    x = np.zeros([n, 1])
    yy = np.array(y, np.float64)

    for i in range(n - 1, -1, -1):
        for j in range(i + 1, n):
            yy[i] = yy[i] - U[i, j] * x[j]

        if U[i, i] == 0:
            raise Exception('U-Matrix ist singulaer!')
        else:
            x[i] = yy[i] / U[i, i]

    return x

def forwardsubst(L, b):
    # Loese L y = b durch Vorwaerts-Einsetzen (L: linke untere Dreiecksmatrix)
    n = len(b)
    y = np.zeros([n, 1])
    bb = np.array(b, np.float64)
    for i in range(n):
        for j in range(i):
            bb[i] = bb[i] - L[i, j] * y[j]

        if L[i, i] == 0:
            raise Exception('L-Matrix ist singulaer!')
        else:
            y[i] = bb[i] / L[i, i]
    return y

In [19]:
A = np.array([[1, 2, -1], [4, -2, 6], [3, 1, 0]])
b = np.array([9, -4, 9])

In [20]:
# Berechne die LGS-Lösung mithilfe der LU-Zerlegung mit scipy.linalg.lu
from scipy.linalg import lu

P, L, U = lu(A)
P_transposed = P.T
print('P:', P)
print('P transposed:', P_transposed)
print('L:', L)
print('U:', U)

P: [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
P transposed: [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
L: [[1.   0.   0.  ]
 [0.25 1.   0.  ]
 [0.75 1.   1.  ]]
U: [[ 4.  -2.   6. ]
 [ 0.   2.5 -2.5]
 [ 0.   0.  -2. ]]


In [21]:
# Multipliziere b mit P transposed
b_permuted = P_transposed @ b

# Berechne die LGS-Lösung mithilfe der LU-Zerlegung
y = forwardsubst(L, b_permuted)
x = backsubst(U, y)
print('Lösung:', x)

Lösung: [[ 2.]
 [ 3.]
 [-1.]]


/var/folders/br/xflg5m_916s1bn1pdq6h9p3w0000gn/T/ipykernel_4793/1749612531.py:26: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  bb[i] = bb[i] - L[i, j] * y[j]
