# LGS

In [7]:
import numpy as np

In [8]:
def backsubst(U, y):
    # Berechnet die Loesung x von U x = y durch Rueckwaerts-Einsetzen
    # Dabei ist U eine rechte obere Dreiecksmatrix
    n = len(y)
    x = np.zeros([n, 1])
    yy = np.array(y, np.float64)

    for i in range(n - 1, -1, -1):
        for j in range(i + 1, n):
            yy[i] = yy[i] - U[i, j] * x[j]

        if U[i, i] == 0:
            raise Exception('U-Matrix ist singulaer!')
        else:
            x[i] = yy[i] / U[i, i]

    return x

In [9]:
# Example usage
U = np.array([[1, -2, -1], [0, 3, 3], [0, 0, -2]])
y = np.array([3, -6, -6])
x = backsubst(U, y)
print('Lösung\n', x)

Lösung
 [[-4.]
 [-5.]
 [ 3.]]


/var/folders/br/xflg5m_916s1bn1pdq6h9p3w0000gn/T/ipykernel_4755/3327740661.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  yy[i] = yy[i] - U[i, j] * x[j]


In [10]:
def forwardsubst(L, b):
    # Loese L y = b durch Vorwaerts-Einsetzen (L: linke untere Dreiecksmatrix)
    n = len(b)
    y = np.zeros([n, 1])
    bb = np.array(b, np.float64)
    for i in range(n):
        for j in range(i):
            bb[i] = bb[i] - L[i, j] * y[j]

        if L[i, i] == 0:
            raise Exception('L-Matrix ist singulaer!')
        else:
            y[i] = bb[i] / L[i, i]
    return y

In [11]:
L = np.array([[1, 0, 0], [2, 1, 0], [3, 0, 1]])
U = np.array([[1, -2, -1], [0, 3, 3], [0, 0, -2]])
b = np.array([[3], [0], [3]])

y = forwardsubst(L, b)
x = backsubst(U, y)

print('Loesung\n', x)

r = b - (L @ U) @ x
print('Residuum\n', r)


Loesung
 [[-4.]
 [-5.]
 [ 3.]]
Residuum
 [[0.]
 [0.]
 [0.]]
